apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-ic
spec:
  selector:
    matchLabels:
      app: ${app-label}
  replicas: 1
  template:
    metadata:
      labels:
        app: ${app-label}
    spec:
      securityContext:
        runAsUser: 999
      imagePullSecrets:
        - name: image-pull-secret
      serviceAccountName: morganfundsa
      containers:
        - name: ${app-label}