apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aws-ic
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test
  targetCPUUtilizationPercentage: 65
