apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${app-label}
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${app-label}
  targetCPUUtilizationPercentage: 65
