apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: <+pipeline.stages.DeployDEV.variables.app_label>
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <+pipeline.stages.DeployDEV.variables.app_label>