apiVersion: apps/v1
kind: Deployment
metadata:
  name: <+pipeline.stages.DeployDEV.variables.app_label>
spec:
  selector:
    matchLabels:
      app: <+pipeline.stages.DeployDEV.variables.app_label>
  replicas: 1
  template:
    metadata:
      labels:
        app: <+pipeline.stages.DeployDEV.variables.app_label>
    spec:
      securityContext:
        runAsUser: 999
      imagePullSecrets:
        - name: image-pull-secret
      serviceAccountName: morganfundsa
      containers:
        - name: <+pipeline.stages.DeployDEV.variables.app_label>
          image: app-image
          resources:
            requests:
              memory: 6Gi
              cpu: 500m
            limits:
              memory: 8Gi
              cpu: 1000m
          ports:
            - containerPort: 8080
          env:
            # JVM Memory Settings for 1Gi total container memory. Bump the -Xmx setting to match any increase to container memory.
            - name: JAVA_OPTS
              value: -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=512M -XX:ReservedCodeCacheSize=240M -Xss1M -Xmx2048M  -Xms1024M  -Ddd.service.name=<+pipeline.stages.DeployDEV.variables.app_label> -Ddd.trace.global.tags=env:<+pipeline.stages.DeployDEV.variables.env> -Ddd.jmxfetch.enabled=TRUE -Dserver.tomcat.max.threads=800
            # Use X-Forwarded-* headers from Ingress to detect end-client information correctly
            - name: SERVER_USE_FORWARD_HEADERS
              value: "true"
            - name: SERVER_TOMCAT_REMOTEIP_INTERNAL_PROXIES
              value: .*
            # Kubernetes related info for Actuator
            - name: INFO_KUBE_ENV
              value: <+pipeline.stages.DeployDEV.variables.env>
            - name: INFO_KUBE_CLUSTER
              value: <+pipeline.stages.DeployDEV.variables.cluster>
            - name: INFO_KUBE_IMAGE
              value: <+artifact.image>
            - name: INFO_KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INFO_KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INFO_KUBE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: INFO_KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DD_ENV
              value: <+pipeline.stages.DeployDEV.variables.env>
            - name: DD_VERSION
              value: <+artifact.image>
            - name: DD_APM_ENABLED
              value: "true"
            - name: DD_APM_NON_LOCAL_TRAFFIC
              value: "true"
            - name: DD_PROXY_NO_PROXY
              value: "localhost,127.0.0.1,169.254.169.254,100.69.68.160/27,100.69.68.128/27,100.72.64.0/18,100.72.0.0/18,100.72.32.0/19,100.72.96.0/19,100.72.0.0/19,100.72.64.0/19,100.74.29.192/27,100.74.29.128/27,100.74.29.224/27,100.74.29.160/27,100.72.0.0/19,100.72.64.0/19,100.72.32.0/19,100.72.96.0/19,100.74.125.224/27,100.74.125.192/27,100.74.125.128/27,100.74.125.160/27"
            - name: DD_KUBELET_TLS_VERIFY
              value: "false"
            - name: DD_PROXY_HTTPS
              value: "http://proxy.jpmchase.net:10443"
            - name: DD_LOGS_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_JMXFETCH_ENABLED
              value: "true"
            - name: DATADOG_TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_SERVICE_NAME
              value: "<+pipeline.stages.DeployDEV.variables.app_label>"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: AWS_STS_REGIONAL_ENDPOINTS
              value: regional
          envFrom:
            - configMapRef:
                name: <+pipeline.stages.DeployDEV.variables.app_label>-runtime
          readinessProbe:
            httpGet:
              path: <+pipeline.stages.DeployDEV.variables.context_path>/actuator/keepalive
              port: 8080
            timeoutSeconds: 5
            initialDelaySeconds: 70
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: <+pipeline.stages.DeployDEV.variables.context_path>/actuator/keepalive
              port: 8080
            timeoutSeconds: 5
            initialDelaySeconds: 70
            periodSeconds: 10